language: c

addons:
  apt:
    packages:
      - xorg-dev
      - libglu1-mesa-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
      compiler: gcc

    - os: linux
      dist: bionic
      arch: amd64
      compiler: clang

    - os: linux
      dist: focal
      arch: amd64
      compiler: gcc

    - os: linux
      dist: focal
      arch: amd64
      compiler: clang


    - os: osx
      compiler: clang
      osx_image: xcode12.2

    - os: linux
      dist: focal
      arch: arm64
      compiler: gcc

    - os: osx
      compiler: clang
      osx_image: xcode10.3

    - os: osx
      compiler: clang
      osx_image: xcode11.6

    - os: osx
      compiler: clang
      osx_image: xcode12

  allow_failures:
    - os: linux
      arch: arm64

    - os: osx
